//
//  CreateOrderPresenter.swift
//  CleanStore
//
//  Created by Victor Souza on 2/17/16.
//  Copyright (c) 2016 Victor Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CreateOrderPresenterInput {
    
    func presentExpirationDate(response: CreateOrder_FormatExpirationDate_Response)
}

protocol CreateOrderPresenterOutput: class {
    
    func displayExpirationDate(viewModel: CreateOrder_FormatExpirationDate_ViewModel)
}

class CreateOrderPresenter: CreateOrderPresenterInput {
    
    weak var output: CreateOrderPresenterOutput!
    let dateFormatter: NSDateFormatter = {
        let dateFormatter = NSDateFormatter()
        dateFormatter.dateStyle = .ShortStyle
        dateFormatter.timeStyle = NSDateFormatterStyle.NoStyle
        return dateFormatter
    }()
    
    // MARK: Presentation logic
    
    // MARK: Expiration date
    
    func presentExpirationDate(response: CreateOrder_FormatExpirationDate_Response) {
        
        let date = dateFormatter.stringFromDate(response.date)
        let viewModel = CreateOrder_FormatExpirationDate_ViewModel(date: date)
        output.displayExpirationDate(viewModel)
    }
}
