//
//  CreateOrderModels.swift
//  CleanStore
//
//  Created by Victor Souza on 2/17/16.
//  Copyright (c) 2016 Victor Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Request Model

struct CreateOrder_FormatExpirationDate_Request {
    
    var date: NSDate
}

// MARK: Response Model

struct CreateOrder_FormatExpirationDate_Response {
    
    var date: NSDate
}

// MARK: View Model

struct CreateOrder_FormatExpirationDate_ViewModel {
    
    var date: String
}