//
//  DeleteOrderModels.swift
//  CleanStore
//
//  Created by Victor Souza on 2/19/16.
//  Copyright (c) 2016 Victor Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Request Model

struct DeleteOrderRequest {
    
}

// MARK: Response Model

struct DeleteOrderResponse {
    
}

// MARK: View Model

struct DeleteOrderViewModel {
    
}
