//
//  ListOrdersWorker.swift
//  CleanStore
//
//  Created by Victor Souza on 2/18/16.
//  Copyright (c) 2016 Victor Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class ListOrdersWorker {
    
    // MARK: Business Logic
    
    func doSomeWork() {
        
        // NOTE: Do the work
    }
}
