//
//  OrdersWorker.swift
//  CleanStore
//
//  Created by Victor Souza on 2/18/16.
//  Copyright (c) 2016 Victor Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol OrdersStoreProtocol {
    
    func fetchOrders(completionHandler: (orders: [Order]) -> Void)
}

class OrdersWorker {
    
    var ordersStore: OrdersStoreProtocol
    
    init(ordersStore: OrdersStoreProtocol) {
        
        self.ordersStore = ordersStore
    }
    
    // MARK: Business Logic
    
    func fetchOrders(completionHandler: (orders: [Order]) -> Void) {
        
        ordersStore.fetchOrders { (orders: [Order]) -> Void in
            completionHandler(orders: orders)
        }
    }
}
